name: continuous-deployment-hml
on:
  push:
    branches:
      - master

jobs:
  smoke-tests:
    runs-on: ubuntu-16.04
    timeout-minutes: 15
    steps:
        - name: Checkout
          uses: actions/checkout@v1
        
        - name: Install dependencies
          run: npm
